name: Continous deployments with github and docker
on:
  push:
    branches:
      - fix/27/docker-learning
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false
      - name: Set up QEMU for docker
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx for the build
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub using the given the credentials and upload file
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Build and push the file using DockerFile
        uses: docker/build-push-action@v5
        with:
          context: deploy/docker
          push: true
          tags: danasekaraneta/mlflowlearning:github-latest
