name: Pull the MLFlow Image from DockerHub and run
on:
  push:
    branches:
      - mlflow-docker-pull
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: false
          
      - name: Set up QEMU for docker
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx for the build
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub using the the credentials
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Pull the docker image from DockerHub
        run: docker pull danasekaraneta/mlflowlearning:github-latest

      - name: Run the pulled image
        run : docker run -p 8080:5008 --name mlflowlearning danasekaraneta/mlflowlearning:github-latest

      - name: Run application completed status
        run: |
          echo "MLflow App run completed successfully.!"
          sleep 10
          echo "All done.!!"
