name: Test the Housing Price Prediction Module installed or not

on:
  push:
    branches:
      - main
      - fix/11/testing-code-with-pytest

jobs:
  Test_Housing_Pricing:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mle-dev
          environment-file: etc/env.yml
          auto-activate-base: false

      - name: Install Tree Cli
        run: |
          sudo apt install tree

      - name: Tree before building the package
        run: |
          tree

      - name: Build Package Locally
        run: |
          pip install --upgrade setuptools
          pip install --upgrade build
          pip install -U pytest
          python -m build

      - name: Tree after building the package
        run: |
          tree
      - name: Install Package locally
        run: |
          pip install dist/*.whl
      - name: Run the test case using Pytest
        run: |
          pytest tests/test_packages.py