name: Test the Housing Price Prediction with the local package install version

on:
  push:
    branches:
      - main
      - fix/15/unit-testing

jobs:
  Test_Module_Package:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mle-dev
          environment-file: deploy/env.yml
          auto-activate-base: false

      - name: Install Tree Cli
        run: |
          sudo apt install tree

      - name: Tree before building the package
        run: |
          tree

      - name: Run the test case using Pytest without local package this will fail
        run: |
            pip install -U pytest
            pytest -v

      - name: Build Package Locally
        run: |
          pip install -e .

      - name: Tree after building the package
        run: |
          tree
      - name: Run the test case using Pytest
        run: |
          pytest -v