name: Workflow Logger

on:
  pull_request:
    branches:
      - main
      - fix/19/python-logging

jobs:
  Build_Job:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: myenv
          environment-file: deploy/env.yml
          auto-activate-base: false

      - name: Build Package
        run: |
          pip install --upgrade setuptools
          pip install --upgrade build
          python -m build
          pip install -U pytest

      - name: Install Package
        run: |
          pip install dist/*.whl

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts_upload
          path: dist/

  Deploy_job:
    needs: [Build_Job]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: mle-dev
          environment-file: deploy/conda/env.yml
          auto-activate-base: false

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifacts_upload
          path: dist/

      - name: Install the downloaded artifacts
        run: |
          pip install dist/*.whl

      - name: Run scripts
        run: |
          python scripts/ingestion.py -h
          python scripts/ingestion.py data
          python scripts/train.py -h
          python scripts/train.py data/processed .artifacts/models
          python scripts/score.py -h
          python scripts/score.py data/processed .artifacts/models .artifacts/scores
